### ISSUE TITLE
Missing model file

### ISSUE THREAD

**Issue by jcrossley3** [danbev/learning-ai#6]
https://github.com/danbev/learning-ai/blob/efa09253819800535d33451c629fdf93f195d90c/fundamentals/rust/llm-chains-chat-demo/src/main-llama.rs#L113

I grabbed one from [here](https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGUF/blob/5db6994dca7288297c59693b5e27b62f22a54e1f/llama-2-7b-chat.Q4_0.gguf) and everything ran fine, but seems like there should be some mention of it in the README maybe?

**Comment by danbev** [comment]
Good point, let me add a download command to the README.md that stores this in the modules directory. Thanks!
